### ISSUE TITLE
Problème de traduction de la zone "titre et sous-titre"

### ISSUE THREAD

**Issue by Offirmo** [themesdefrance/Etendard#416]
Dans la zone "titre et sous-titre" d'une page d'accueil, ces deux champs ne sont pas traduits alors que le reste du contenu l'est, ex. http://demoetendard-ef001.rhcloud.com/ en cliquant sur les drapeaux à gauche.

Ces champs sont pourtant bien traduits dans polylang
![polylang](https://cloud.githubusercontent.com/assets/603503/9737152/7d5334a0-5645-11e5-8919-3eb3481f5c1a.png)

**Comment by themesdefrance** [comment]
Bonjour,

Le thème n'est pas vraiment optimisé pour les plugins multinlingues, d'où le problème de traduction.

**Comment by Offirmo** [comment]
Dommage :-( Beaucoup de clients veulent une version en anglais... Et pourtant les autres contenus (projets, services) se traduisent bien...

**Comment by themesdefrance** [comment]
En fait, ces deux valeurs sont enregistrées en tant qu'options, d'ou la non traduction. Les types de contenus ne fonctionne pas de la même façon, d'où la compatibilité
