### ISSUE TITLE
L'appel à l'action ne s'affiche pas en page d'accueil

### ISSUE THREAD

**Issue by Offirmo** [themesdefrance/Etendard#417]
L'appel à l'action est activé :
![appel a l action](https://cloud.githubusercontent.com/assets/603503/9737178/a34e4a1e-5645-11e5-98d1-8006056a7f33.png)

et configuré
![reglages appel a l action](https://cloud.githubusercontent.com/assets/603503/9737214/ca85bc8e-5645-11e5-8fcb-310685d3868b.png)

et rien ne s'affiche http://demoetendard-ef001.rhcloud.com/

**Comment by themesdefrance** [comment]
Pouvez-vous m'envoyer un accès au site pour que je puisse jeter un oeil ?

**Comment by Offirmo** [comment]
accès envoyé par mail

**Comment by themesdefrance** [comment]
L'appel à l'action n'est pas configuré sur la page d'accueil, donc il ne s'affiche pas : 

![capture d ecran 2015-09-11 a 10 19 19](https://cloud.githubusercontent.com/assets/5429694/9810148/9800e8b2-586e-11e5-9007-fbd4aa43afa2.png)

L'appel à l'action complété est celui du portfolio

**Comment by Offirmo** [comment]
Mais alors à quoi correspond la config de l'appel à l'action dans Apparence > réglages étendard ?? (cf. ma capture d'écran ci-dessus)

Doublon ?

**Comment by themesdefrance** [comment]
Comme indiqué sous mon image, il s'agit de l'appel à l'action du portfolio (sous chaque projet)
